// 媒体の基本設定。ドメインが決まったら site を差し替える（GitHub Pages の間は github.io）。
export const SITE = {
  name: "The Sake Wire",
  tagline: {
    en: "Japan's sake news, now in Europe. Sake, shochu, whisky, wine and beer — and the events where you can taste them.",
    nl: "Nieuws over Japanse sake, nu in Europa. Sake, shochu, whisky, wijn en bier — en de evenementen waar je ze proeft.",
    de: "Japans Sake-Nachrichten, jetzt in Europa. Sake, Shochu, Whisky, Wein und Bier – und die Events, bei denen man sie probiert.",
    es: "Las noticias del sake japonés, ahora en Europa. Sake, shochu, whisky, vino y cerveza — y los eventos donde probarlos.",
    ja: "日本のお酒の今を、世界へ。世界のお酒の現場を、日本へ。日本酒・焼酎・ウイスキー・ワイン・ビールとイベント情報。",
  },
  shop: "https://shop.made-in-akita.com",
  about: "https://shop.made-in-akita.com/pages/about",
  producers: "https://shop.made-in-akita.com/pages/producers",
  instagram: "https://www.instagram.com/made_in_akita/",
  langs: ["en", "nl", "de", "es", "ja"] as const,
  langNames: { en: "English", nl: "Nederlands", de: "Deutsch", es: "Español", ja: "日本語" },
  ui: {
    en: { latest: "Latest", source: "Source", readMore: "Read more", shopCta: "Shop Akita sake in the EU", akita: "Akita", allNews: "All stories", published: "Published", drink: "Enjoy responsibly. 18+ (20+ in SE/LT/JP).", sources: "Sources", sourcesNote: "This article was written by The Sake Wire editorial team, summarising the public sources listed above. Images are our own." },
    nl: { latest: "Laatste", source: "Bron", readMore: "Lees verder", shopCta: "Akita-sake kopen in de EU", akita: "Akita", allNews: "Alle verhalen", published: "Gepubliceerd", drink: "Geniet met mate. 18+ (20+ in SE/LT/JP).", sources: "Bronnen", sourcesNote: "Dit artikel is geschreven door de redactie van The Sake Wire op basis van de bovenstaande openbare bronnen. De beelden zijn van onszelf." },
    de: { latest: "Aktuell", source: "Quelle", readMore: "Weiterlesen", shopCta: "Akita-Sake in der EU kaufen", akita: "Akita", allNews: "Alle Beiträge", published: "Veröffentlicht", drink: "Bitte verantwortungsvoll genießen. 18+ (20+ in SE/LT/JP).", sources: "Quellen", sourcesNote: "Dieser Beitrag wurde von der Redaktion von The Sake Wire auf Grundlage der oben genannten öffentlichen Quellen verfasst. Die Bilder stammen von uns." },
    es: { latest: "Lo último", source: "Fuente", readMore: "Leer más", shopCta: "Compra sake de Akita en la UE", akita: "Akita", allNews: "Todas las historias", published: "Publicado", drink: "Disfruta con responsabilidad. 18+ (20+ en SE/LT/JP).", sources: "Sources", sourcesNote: "This article was written by The Sake Wire editorial team, summarising the public sources listed above. Images are our own." },
    ja: { latest: "最新", source: "出典", readMore: "続きを読む", shopCta: "EUで秋田の酒を買う", akita: "秋田", allNews: "すべての記事", published: "公開", drink: "お酒は20歳（EUでは18歳・SE/LTは20歳）になってから。", sources: "参考・出典", sourcesNote: "本記事は上記の公開情報をもとに The Sake Wire 編集部が要約・執筆したものです。画像は自社素材を使用しています。" },
  },
};
export const NAV: Record<Lang, { news: string; events: string; breweries: string; about: string; shop: string; shopNote: string }> = {
  en: { news: "News", events: "Events", breweries: "Breweries", about: "About", shop: "Shop", shopNote: "Ships from Amsterdam · EU €12.95" },
  nl: { news: "Nieuws", events: "Evenementen", breweries: "Brouwerijen", about: "Over ons", shop: "Shop", shopNote: "Verzonden uit Amsterdam · NL €10 · iDEAL" },
  de: { news: "News", events: "Events", breweries: "Brauereien", about: "Über uns", shop: "Shop", shopNote: "Versand aus Amsterdam · EU €12,95" },
  es: { news: "Noticias", events: "Eventos", breweries: "Bodegas", about: "Sobre nosotros", shop: "Tienda", shopNote: "Envío desde Ámsterdam · UE €12,95" },
  ja: { news: "ニュース", events: "イベント", breweries: "蔵元", about: "About", shop: "ショップ", shopNote: "アムステルダムから EU 全域へ発送" },
};
export const MOD: Record<Lang, Record<string, string>> = {
  en: { brandTitle: "What is MADE IN AKITA?", brandText: "The Sake Wire is published by MADE IN AKITA, a small importer in Amsterdam that brings sake, wine, beer and gin from independent producers in Akita, northern Japan, to the whole EU — including 180 ml tasting bottles so you can try before you commit.", brandShop: "See the shop", brandAbout: "Our story", taste: "Taste this style", tasteSub: "Bottles from our Amsterdam warehouse that match this story", order: "Order", ships: "ships from Amsterdam", weekly: "This week's bottles", weeklySub: "Three picks from the shelf", ctaTitle: "Try Akita sake in the EU — from €6", ctaText: "180 ml tasting bottles and full-size sake, wine, beer and gin, shipped from Amsterdam within the EU.", ctaBtn: "Shop now", newsTitle: "The weekly wire", newsText: "One email a week: the stories, the events, the new bottles.", newsBtn: "Subscribe", newsPh: "you@example.com", akitaTitle: "Our producers in Akita", akitaText: "The breweries behind MADE IN AKITA's bottles.", related: "More stories", share: "Share", toc: "In this story", from: "from", events: "Events", eventsSoon: "Event listings are coming: tastings, competitions and festivals in Europe and Japan.", latest: "Latest" },
  nl: { brandTitle: "Wat is MADE IN AKITA?", brandText: "The Sake Wire wordt uitgegeven door MADE IN AKITA, een kleine importeur in Amsterdam die sake, wijn, bier en gin van onafhankelijke producenten uit Akita (Noord-Japan) naar de hele EU brengt — inclusief 180 ml proefflesjes.", brandShop: "Naar de shop", brandAbout: "Ons verhaal", taste: "Proef deze stijl", tasteSub: "Flessen uit ons Amsterdamse magazijn die bij dit verhaal passen", order: "Bestellen", ships: "verzonden uit Amsterdam", weekly: "Flessen van de week", weeklySub: "Drie keuzes uit het schap", ctaTitle: "Proef Akita-sake in Nederland — vanaf €6", ctaText: "180 ml proefflesjes en volle flessen sake, wijn, bier en gin, verzonden uit Amsterdam. NL €10, afhalen gratis, iDEAL.", ctaBtn: "Naar de shop", newsTitle: "De wekelijkse wire", newsText: "Eén e-mail per week: de verhalen, de evenementen, de nieuwe flessen.", newsBtn: "Inschrijven", newsPh: "jij@voorbeeld.nl", akitaTitle: "Onze producenten in Akita", akitaText: "De brouwerijen achter de flessen van MADE IN AKITA.", related: "Meer verhalen", share: "Delen", toc: "In dit verhaal", from: "vanaf", events: "Evenementen", eventsSoon: "Evenementen komen eraan: proeverijen, wedstrijden en festivals in Europa en Japan.", latest: "Laatste" },
  de: { brandTitle: "Was ist MADE IN AKITA?", brandText: "The Sake Wire wird von MADE IN AKITA herausgegeben, einem kleinen Importeur in Amsterdam, der Sake, Wein, Bier und Gin unabhängiger Produzenten aus Akita (Nordjapan) in die ganze EU bringt – inklusive 180-ml-Probierflaschen.", brandShop: "Zum Shop", brandAbout: "Unsere Geschichte", taste: "Diesen Stil probieren", tasteSub: "Flaschen aus unserem Amsterdamer Lager, die zu dieser Geschichte passen", order: "Bestellen", ships: "Versand aus Amsterdam", weekly: "Flaschen der Woche", weeklySub: "Drei Empfehlungen aus dem Regal", ctaTitle: "Akita-Sake in der EU probieren – ab €6", ctaText: "180-ml-Probierflaschen und volle Flaschen Sake, Wein, Bier und Gin, Versand aus Amsterdam innerhalb der EU.", ctaBtn: "Zum Shop", newsTitle: "Der wöchentliche Wire", newsText: "Eine E-Mail pro Woche: die Geschichten, die Events, die neuen Flaschen.", newsBtn: "Abonnieren", newsPh: "du@beispiel.de", akitaTitle: "Unsere Produzenten in Akita", akitaText: "Die Brauereien hinter den Flaschen von MADE IN AKITA.", related: "Weitere Beiträge", share: "Teilen", toc: "In diesem Beitrag", from: "ab", events: "Events", eventsSoon: "Event-Listen folgen: Verkostungen, Wettbewerbe und Festivals in Europa und Japan.", latest: "Aktuell" },
  es: { brandTitle: "¿Qué es MADE IN AKITA?", brandText: "The Sake Wire lo publica MADE IN AKITA, un pequeño importador de Ámsterdam que lleva sake, vino, cerveza y ginebra de productores independientes de Akita (norte de Japón) a toda la UE, con botellas de degustación de 180 ml.", brandShop: "Ver la tienda", brandAbout: "Nuestra historia", taste: "Prueba este estilo", tasteSub: "Botellas de nuestro almacén de Ámsterdam que encajan con esta historia", order: "Pedir", ships: "envío desde Ámsterdam", weekly: "Las botellas de la semana", weeklySub: "Tres elecciones de la estantería", ctaTitle: "Prueba el sake de Akita en la UE — desde €6", ctaText: "Botellas de degustación de 180 ml y botellas completas de sake, vino, cerveza y ginebra, enviadas desde Ámsterdam dentro de la UE.", ctaBtn: "Ir a la tienda", newsTitle: "El wire semanal", newsText: "Un correo a la semana: las historias, los eventos, las botellas nuevas.", newsBtn: "Suscribirse", newsPh: "tu@ejemplo.es", akitaTitle: "Nuestros productores en Akita", akitaText: "Las bodegas detrás de las botellas de MADE IN AKITA.", related: "Más historias", share: "Compartir", toc: "En esta historia", from: "desde", events: "Eventos", eventsSoon: "Pronto: catas, concursos y festivales en Europa y Japón.", latest: "Lo último" },
  ja: { brandTitle: "MADE IN AKITA とは", brandText: "The Sake Wire の発行元 MADE IN AKITA は、アムステルダムの小さな輸入業者。秋田の独立系の造り手の日本酒・ワイン・ビール・ジンを、180ml のお試しサイズも含めて EU 全域に届けています。", brandShop: "ショップを見る", brandAbout: "私たちについて", taste: "この記事の味わい方", tasteSub: "この話に合う、アムステルダム倉庫のボトル", order: "注文する", ships: "アムステルダムから発送", weekly: "今週のボトル", weeklySub: "棚から3本", ctaTitle: "秋田の酒を EU で試す — €6 から", ctaText: "180ml のお試しサイズと、日本酒・ワイン・ビール・ジンのフルボトル。アムステルダムから EU 域内へ発送。", ctaBtn: "ショップへ", newsTitle: "週刊 The Sake Wire", newsText: "週1通のメール：記事、イベント、新着ボトル。", newsBtn: "登録する", newsPh: "you@example.com", akitaTitle: "秋田の造り手たち", akitaText: "MADE IN AKITA のボトルを醸す蔵元。", related: "ほかの記事", share: "シェア", toc: "この記事の内容", from: "〜", events: "イベント", eventsSoon: "イベント情報を準備中：欧州と日本の試飲会・コンクール・祭り。", latest: "最新" },
};
export const CATEGORY: Record<string, Record<string, string>> = {
  "新商品": { en: "New release", nl: "Nieuw product", de: "Neuheit", es: "Novedad", ja: "新商品" },
  "受賞": { en: "Awards", nl: "Onderscheiding", de: "Auszeichnung", es: "Premios", ja: "受賞" },
  "輸出": { en: "Export", nl: "Export", de: "Export", es: "Exportación", ja: "輸出" },
  "蔵元": { en: "Breweries", nl: "Brouwerijen", de: "Brauereien", es: "Bodegas", ja: "蔵元" },
  "酒米": { en: "Sake rice", nl: "Sakerijst", de: "Sake-Reis", es: "Arroz para sake", ja: "酒米" },
  "イベント": { en: "Events", nl: "Evenementen", de: "Veranstaltungen", es: "Eventos", ja: "イベント" },
  "行政": { en: "Policy", nl: "Beleid", de: "Politik", es: "Política", ja: "行政" },
  "研究": { en: "Research", nl: "Onderzoek", de: "Forschung", es: "Investigación", ja: "研究" },
  "その他": { en: "Stories", nl: "Verhalen", de: "Geschichten", es: "Historias", ja: "話題" },
};
export const catLabel = (c: string | undefined, l: Lang) => (c && CATEGORY[c]?.[l]) || c || "";
export type Lang = (typeof SITE.langs)[number];
